### ISSUE TITLE
Delete Audit account baseline (usecase/base-ct-audit)

### ISSUE THREAD

**Issue by ohmurayu** [aws-samples/baseline-environment-on-aws#237]
ControlTower create SNS Topic in an Audit account to notify all of the configuration change events in all of the member account.
base-ct-audit usecase create stack to subscribe the SNS topic and notify it to slack.
However, in real world, no one want to get notify from the topic because so many events are published to that topic.

So we should delete that usecase and just inform in BLEA document about the fact that the topic exists.
PR is already created in #221. Documents are need to be updated. (doc/DeployToControlTower.md, doc/DeployToControlTower_ja.md)

Topic ARN is arn:aws:sns:${controltowerHomeRegion}:${controltowerAuditAccountId}:aws-controltower-AggregateSecurityNotifications
from  usecases/base-ct-audit/bin/blea-base-ct-audit.ts

**Comment by konokenj** [comment]
Fixed by releasing v3.0.0.
