### ISSUE TITLE
Supporting Node v18 in the Build System

### ISSUE THREAD

**Issue by watany-dev** [aws-samples/baseline-environment-on-aws#260]
I'm leaving some notes on the build aspects I noticed while working on the Pull Request.

- Currently, the .github/workflows/build.yml configuration is set to build with node v14 and v16, but the latest LTS is v18. As you can see from the website below, the end-of-life (EOL) is approaching in about a month or five months. It seems like a good idea to add v18 temporarily and see how it goes.
https://endoflife.date/nodejs

- Related to this, I believe that gitlab-ci.yml should also support node v18. However, the necessity of this file is unclear, so I withdrew the PR.
https://github.com/aws-samples/baseline-environment-on-aws/pull/259

**Comment by konokenj** [comment]
@watany-dev Sorry for late reply. I agree that we should use Node.js 18 now because aws-cdk suggests to use active LTS. 
And we will continue to support building and testing with GitLab CI.
