### ISSUE TITLE
CREATE_FAILED: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting

### ISSUE THREAD

**Issue by TakeshiMogami** [aws-samples/baseline-environment-on-aws#295]
新規にcdk deployを実行する際にBLEA-BASE-TrailスタックのArchiveLogsBucket作成時に
```
Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting
```
というエラーでスタック作成が失敗します。

恐らく下記のS3の仕様変更の影響です。
https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/access-control-block-public-access.html
https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/create-bucket-faq.html
https://aws.amazon.com/jp/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

**Comment by TakeshiMogami** [comment]
# 原因
usecases\base-standalone\lib\blea-trail-stack.ts において下記の箇所でACLを設定しているのですが、
２０２３年４月からデフォルトでACLが無効になったためCloudFormation実行時にエラーになります。
```
    // Archive Bucket for CloudTrail
    const archiveLogsBucket = new s3.Bucket(this, 'ArchiveLogsBucket', {
      accessControl: s3.BucketAccessControl.LOG_DELIVERY_WRITE,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
```

# 対策方法
accessControlの設定を削除して、その代わりに
コンテキストオプション"@aws-cdk/aws-s3:serverAccessLogsUseBucketPolicy" 
を使用する事で正常にバケットを作成できるようです。
このオプションはcdk initコマンドで新規プロジェクトを作成した時にデフォルトで作成されるcdk.jsonに自動的に設定される多数のオプションの内の一つです。

**Comment by ohmurayu** [comment]
Thank you for reaching out.
We are aware of this issue and will be fix this soon. Thanks.

**Comment by konokenj** [comment]
This issue is fixed by #296 and be merged into main.
