### ISSUE TITLE
Replace old aws-portal:*Billing action in sample IAM policies

### ISSUE THREAD

**Issue by konokenj** [aws-samples/baseline-environment-on-aws#421]
BLEA creates some sample IAM Roles that include deprecated IAM action `aws-portal:*Billing` that should be replaced equivalent policies.

![image](https://github.com/aws-samples/baseline-environment-on-aws/assets/93309555/bf317ac3-cd03-45b2-afe4-9272d66dc291)

https://aws.amazon.com/jp/blogs/news/changes-to-aws-billing-cost-management-and-account-consoles-permissions/
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/migrate-granularaccess-iam-mapping-reference.html

**Comment by suzukyz** [comment]
This issues was resolved by #583 .
