### ISSUE TITLE
Resources created by Standalone feel unclear

### ISSUE THREAD

**Issue by watany-dev** [aws-samples/baseline-environment-on-aws#49]
I couldn't figure out the scope of this tool in the Standalone (With Individual account) diagram.  (For example, IAM Access Analyzer is not in the CDK code.) It is very helpful to recommend the use to the surrounding users if you color it with gray etc. like Multi-Account (With Control Tower).

**Comment by watany-dev** [comment]
By the way, for IAM Access Analyzer, I could create that feature if it's an implementation like this one :)

https://dev.classmethod.jp/articles/create-analyzer-all-region/

**Comment by ohmurayu** [comment]
Thank you for comment. I can understand your point. We'll check docs.

**Comment by ohmurayu** [comment]
Updated architecture diagram in #56 to clarify which services are supported by manual operation or CDK template.
Thank you for your feedback!
