### ISSUE TITLE
2023/11/16

### ISSUE THREAD

**Issue by akihiko-saijou** [aws-samples/baseline-environment-on-aws#564]
### 本営業日やること
凡例 X: Done, P: 後でやる

* 10時50分 リアル出社@歌舞伎座
* やることリスト整理
* 11:00 AM-11:20 AM 論理 Daily Sync
  * 昨日の生のansible LB設定チケットが緊急になった
* [SKIP] 2:00 PM-3:00 PM 論理 Weekly Sync
* 下期目標草稿作成
  * https://wiki.ict.kadokawa.jp/pages/viewpage.action?pageId=269749024
* SmilePJ:
  * cdkベストプラクティス
    * https://aws.amazon.com/jp/blogs/news/best-practices-for-developing-cloud-applications-with-aws-cdk/
  * cdk/ecspresso
    * VPC, クラスタ、SSMをCDKで構築
      * パラメータはSSMで管理
    * タスク、サービスはecspressoで管理
  * belaのecsリポジトリ
    * https://github.com/aws-samples/baseline-environment-on-aws/blob/main/doc/PipelineDeployment_ja.md
* コンプライアンスアンケート~11/17
* AWS re:inventセッション登録
* 3:00 PM-4:00 PM Cloud Native課Weekly Sync
  * Dwangoの方針で荒れている
  * 今週中に目標作成
  * 来週木曜にrecapやる？
* 従業員満足度調査　X
* 4:00 PM-4:30 PM 堀内さんdaily
  * GuardDuty
* 4:30 PM-5:00 PM 【smilePJ】DOLのインフラ管理移管のご相談
  * クルービット濵中
  * スケジュール12月を予定
  * 現在のレコードを送ってもらう
  * WAFなし
    * EC2内でIPを弾いたりはしている
    * 設定を送ってもらう
  * コミュニケーション：backlog/slack
  * (WAFないというのは結構やばいのかも。コスト予算をしっかりめに確認する必要がある。とはいえ、
* 6:00 PM-7:00 PM もくもく会
  * aws資格勉強 X
  * そろそろ予約を入れる
* 19時10分 退社

### 翌営業日やること

* 予定チェック

**Comment by ohmurayu** [comment]
This issue seems sent accidentally. 
@akihiko-saijou Could you kindly check this issue and modify if you need, as we can't remove issues by our policy.
