### ISSUE TITLE
EC2 Launch configurations is deprecated

### ISSUE THREAD

**Issue by tomoki10** [aws-samples/baseline-environment-on-aws#60]
## Describe the issue

In the following source code, instanceType, machineImage are set as options for launching EC2. This causes Launch Configurations to be used.

https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/usecases/guest-webapp-sample/lib/blea-ec2app-stack.ts#L135-L138

https://github.com/aws-samples/baseline-environment-on-aws/blob/1df2898abc9769d926617ae548f1d5af27979097/usecases/guest-webapp-sample/lib/blea-asgapp-stack.ts#L70-L73

Launch Configurations is deprecated. Currently, the use of Launch templates is recommended.
References: https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-configurations.html

### Possible Solution
Rewrite to use Launch templates.
```
launchTemplate: new ec2.LaunchTemplate(this, "", {...}),
```

### A reproducible test case or series of steps

1. Deploy the following sources
```
usecases/guest-webapp-sample/bin/blea-guest-asgapp-sample.ts
```
2. Check EC2 Auto Scaling settings in the AWS console.

### The version of our code being used
now latest commit version: https://github.com/aws-samples/baseline-environment-on-aws/commit/1df2898abc9769d926617ae548f1d5af27979097

## Other information
I can be implemented this issue. If there is no problem, I will create a Pull Request.

**Comment by konokenj** [comment]
Thank you for your reporting. We agree this proposal. Pull request is welcome :)

**Comment by tomoki10** [comment]
@konokenj 
Thank you for confirmation.
I'm contacting you because I have confirmed one misunderstanding and one that we are currently unable to accommodate.
- blea-ec2app-stack.ts did not use Launch Configurations, so it did not matter.
- auto-scaling-group.ts did not support Launch templates until CDK version v2.21.0 or later.
  - https://github.com/aws/aws-cdk/releases/tag/v2.21.0
  - https://github.com/aws/aws-cdk/pull/19066
  The current version of CDK at BLEA appears to be v2.8.0 when checking package-lock.json.
  If there is a plan to update the CDK version, we will start after that.

**Comment by konokenj** [comment]
@tomoki10 Sorry for late reply. Now we know BLEA should follow CDK updates continuously. I'm on work updating dependency.

**Comment by konokenj** [comment]
@tomoki10 We have updated CDK to v2.38.1 with PR #62.
