### ISSUE TITLE
The runtime aws_synthetics.Runtime.SYNTHETICS_NODEJS_PUPPETEER_3_5 has been deprecated

### ISSUE THREAD

**Issue by miya10** [aws-samples/baseline-environment-on-aws#652]
The CloudWatch Synthetics runtime (`SYNTHETICS_NODEJS_PUPPETEER_3_5`) has already been deprecated as of January 8, 2024. As a result, a guest template (ECS+SSL) deployment using CDK fails.
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html

Affected code section (ECS+SSL sample app):
https://github.com/aws-samples/baseline-environment-on-aws/blob/3410efbf512d198e4a914a235db8081104f2adb4/usecases/blea-guest-ecs-app-sample/lib/construct/canary.ts#L53

I needed to specify a version equal to or greater than `syn-nodejs-puppeteer-4.0` (fyi: I have verified successful deployment using `syn-nodejs-puppeteer-6.0`).

**Comment by konokenj** [comment]
Thank you for reporting. This is fiexed by #662.
