### ISSUE TITLE
Use NODEJS_20_X

### ISSUE THREAD

**Issue by trivikr** [aws-samples/baseline-environment-on-aws#785]
### Use Case

Lambda NODEJS_14_X runtime is used in one sample https://github.com/search?q=repo%3Aaws-samples%2Fbaseline-environment-on-aws%20NODEJS_14_X&type=code

It's function create is blocked as of `Jan 9, 2024`.
Lambda Supported Runtimes https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

### Proposed Solution

Use NODEJS_20_X, which [was made available on Nov 15, 2023](https://aws.amazon.com/blogs/compute/node-js-20-x-runtime-now-available-in-aws-lambda/)

**Comment by konokenj** [comment]
Thank you for feedback. This is fixed in #784. Currently, it uses `Runtime.NODEJS_LATEST` that is resolved into Node.js 18.x. See: https://github.com/aws/aws-cdk/blob/9a5d4f023e6ac058075e7eebf9073ae02f79ebbe/packages/aws-cdk-lib/aws-lambda/lib/runtime.ts#L118
